services:
  entities:
    build:
      context: ../../entities
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - PG_URL=${PG_URL}
      - PG_USER=${PG_USER}
      - PG_PWD=${PG_PWD}
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB=${MONGO_DB}
      - OIDC_SERVER_URL=${OIDC_SERVER_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_TRUST_STORE_FILE=${OIDC_TRUST_STORE_FILE}
      - OIDC_TRUST_STORE_PWD=${OIDC_TRUST_STORE_PWD}
      - CERT_FILE=${CERT_FILE}
      - CERT_KEY=${CERT_KEY}
    ports:
      - "8091:8091"
      - "8491:8491"
