services:
  entities:
    build:
      context: .
      dockerfile: ../entities/src/main/docker/Dockerfile.jvm
    environment:
      - PG_URL=${PG_URL}
      - PG_USER=${PG_USER}
      - PG_PWD=${PG_PWD}
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB=${MONGO_DB}
    ports:
      - "8091:8091"
