quarkus:
  container-image:
    builder: docker
  datasource:
    "entities":
      db-kind: postgresql
      username: ${PG_USER}
      password: ${PG_PWD}
      reactive:
        url: ${PG_URL}
  mongodb:
    connection-string: ${MONGO_URL}
    database: ${MONGO_DB}
  # oidc:
  oidc-client:
    auth-server-url: ${OIDC_SERVER_URL}
    client-id: ${OIDC_CLIENT_ID}
    credentials:
      secret: ${OIDC_CLIENT_SECRET}
    tls:
      trust-store-file: ${OIDC_TRUST_STORE_FILE}
      trust-store-password: ${OIDC_KEY_STORE_PWD}
  keycloak:
    policy-enforcer:
      enable: true
  http:
    host: 0.0.0.0
    port: 8091
    root-path: /v1/api
    cors:
      ~: true
      origins: /.*/
      headers: origin,accept,authorization,content-type,x-requested-with
    insecure-requests: disabled
    ssl-port: 8491
    ssl:
      certificate:
        files: ${CERT_FILE}
        key-files: ${CERT_KEY}