services:
  entities:
    build:
      context: ../entities
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - PG_URL=${PG_URL}
      - PG_USER=${PG_USER}
      - PG_PWD=${PG_PWD}
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB=${MONGO_DB}
      - OIDC_SERVER_URL=${OIDC_SERVER_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
    ports:
      - "8091:8091"
