services:
  core:
    build:
      context: ../../middleware
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - PG_URL=${PG_URL}
      - PG_USER=${PG_USER}
      - PG_PWD=${PG_PWD}
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB=${MONGO_DB}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWD=${MQTT_PASSWD}
      - OIDC_SERVER_URL=${OIDC_SERVER_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_TRUST_STORE_FILE=${OIDC_TRUST_STORE_FILE}
      - OIDC_TRUST_STORE_PWD=${OIDC_TRUST_STORE_PWD}
      - CERT_FILE=${CERT_FILE}
      - CERT_KEY=${CERT_KEY}
    ports:
      - "8090:8090"
      - "8490:8490"
